site_name: Gishiki

pages:
- Home: index.md
- Installation: 
    - Environment:          installation/index.md
    - Basic PHP:            installation/basic_php.md
    - PHP 7.0 & nginx:      installation/php_7_nginx.md
    - Basic nginx:          installation/basic_nginx.md
    - Basic apache:         installation/basic_apache.md
    - Basic lighttpd:       installation/basic_lighttpd.md
    - Basic IIS:            installation/basic_iis.md
    - Composer:             installation/composer.md
    - PaaS:                 installation/paas.md
- API: apidoc.md
- Usage:
    - Configuration:    usage/configuration.md
    - Router:           usage/routing.md
    - Request:          usage/request.md
    - Response:         usage/response.md
    - Logger:           usage/logging.md
    - Database:         usage/database.md
    - CRUD:             usage/CRUD.md
- CLI: 
    - CLI Toolkit:          cli/index.md
    
- About:
    - License: license.md

theme: readthedocs
